### ISSUE TITLE
ERROR: [Hsi 55-1592] Current Software Design is not set

### ISSUE THREAD

**Issue by exitrip** [guido57/EBAZ4205_HDMI#1]
Hi,

This is my first time working with Vitis, so maybe this is a dumb question...  But the wrapper project is failing to build from a fresh clone of this repo, and I'm wondering what I'm missing?  I don't see any reference to `Current Software Design` in any of the settings or files (other than build logs).   I ran into this scrubbing the eclipse project of `/media/guido57` paths, specifically thinking that the "export/ebaz4205_wrapper.xpfm" needed is build output of the wrapper project.   Anyway, any help would be appreciated, as there's very little guidance or documentation around the "platform repo" and this error.    Is it unfeasible to commit the export folder?

Cheers,

```
16:16:37 **** Build of project ebaz4205_wrapper ****
buildplatform.sh 45853 ebaz4205_wrapper  
XSDB Server Channel: tcfchan#4
Reading the platform  : "ebaz4205_wrapper"
ERROR: [Hsi 55-1592] Current Software Design is not set
ERROR: [Hsi 55-1592] Current Software Design is not set
ERROR: [Hsi 55-1592] Current Software Design is not set
ERROR: [Hsi 55-1592] Current Software Design is not set
ERROR: [Hsi 55-1592] Current Software Design is not set
ERROR: [Hsi 55-1592] Current Software Design is not set
Reading the platform  : "ebaz4205_wrapper"
ERROR: [Hsi 55-1592] Current Software Design is not set
ERROR: [Hsi 55-1592] Current Software Design is not set
ERROR: [Hsi 55-1592] Current Software Design is not set
ERROR: [Hsi 55-1592] Current Software Design is not set
ERROR: [Hsi 55-1592] Current Software Design is not set
ERROR: [Hsi 55-1592] Current Software Design is not set
No Platform exists with name:  ebaz4205_wrapper
    invoked from within
"::tcf::eval -progress {apply {{msg} {puts $msg}}} {tcf_send_command tcfchan#0 xsdb eval s es {{platform active ebaz4205_wrapper; platform generate }}}"
    (procedure "::tcf::send_command" line 4)
    invoked from within
"tcf send_command $::xsdb::curchan xsdb eval s es [list "platform active $PLATFORM_NAME; platform generate $target"]"
    invoked from within
"if { $iswindows == 1 } {    

    set XSDB_PORT [lindex $argv 0]
    set PLATFORM_NAME [lindex $argv 1]
    set arglen [llength $argv]
    set lastind..."
    (file "/home/aescape/Xilinx/Vitis/2024.1/scripts/vitis/util/buildplatform.tcl" line 11)

16:16:44 Build Finished (took 6s.747ms)
```

**Comment by guido57** [comment]
Hi Exitrip, 

did you:
- build the Vivado project
- exported its hardware, including the Vivado bitstream
- imported the hardware design into Vitis? 

Vitis needs to know how the hardware design is, to load the proper SW libraries and run the colorbars program.

Let me know!

Guido

**Comment by EdBear-Ae** [comment]
Ahh okay, thanks for confirming that the Vitis build is dependent on Vivado output.   

I have had lot's of problems with both Vivado 2022 and 2024.

The first one I hit opening the project is :
![image](https://github.com/user-attachments/assets/201a1f1c-0d8b-4585-a188-42ececea891a)

**Comment by exitrip** [comment]
Ahh okay, thanks for confirming that the Vitis build is dependent on Vivado output.

I have had lot's of problems with both Vivado 2022 and 2024, I think mostly because I updated ip blocks... synth and impl seem to be working if I don't touch anything.

leaving more breadcrumbs about getting the Vitis project to build before I close the issue:
- working with 2024 releases.  Vivado project builds if you don't update any of the IP (no surprises)
- export the xsa file from vivado including bitstream
- checkout v2022.2 from https://github.com/Xilinx/embeddedsw.git and add them as a software repo in Vitis - will complain about some software versions otherwise
- find the `Vitis/ebaz4205_wrapper//platform.tcl` file and modify with paths for your filesystem... 
- then run `xsct` as comments described and click refresh a few times on Vitis's "Project Assitant" tab...   The "system" settings took some tickling to find the new platform files.

I don't have the petalinux sysroot on my system yet, but I get an ELF, so there's something I don't understand about linking in Vitis and file system image generation etc...  but that seems to all live in Petalinux.

Thanks for your help.

**Comment by guido57** [comment]
Thank you for using my repository. Did you succeed in executing "colorbars" on a real hardware with Vitis?

**Comment by exitrip** [comment]
> Thank you for using my repository. Did you succeed in executing "colorbars" on a real hardware with Vitis?

I did!  I can debug on the EBAZ via the Vitis IDE over ethernet.   Now I'm wrestling with trying to get `fpgautil` to load new bit/bin files from the commandline.  Unfortunately my only linux machine right now is on Ubuntu 24.04, which is very not supported by Yocto/petalinux yet, so my only options to change the bitstreams are "live".  I have a new bit and bin output from Vivado, that only changes the HDMI pinout to match an extension board from Aliexpress, so I don't the the DTB files or uboot/kernel should need to change.

 ```
 ebaz4205:~$ fpgautil -b ebaz4205_wrapper.bin -f Full
cp: cannot create regular file '/lib/firmware/ebaz4205_wrapper.bin': Permission denied
sh: line 1: /sys/class/fpga_manager/fpga0/flags: Permission denied
sh: line 1: /sys/class/fpga_manager/fpga0/firmware: Permission denied
rm: cannot remove '/lib/firmware/ebaz4205_wrapper.bin': No such file or directory
BIN FILE loading through FPGA manager failed
ebaz4205:~$ sudo fpgautil -b ebaz4205_wrapper.bin -f Full
Password: 
sh: line 1: echo: write error: Invalid argument
BIN FILE loading through FPGA manager failed
```
... but I doubt this has anything to do with your work or repo...  looks like maybe a version thing from the AMD documentation.

Thanks for your help earlier.

**Comment by exitrip** [comment]
I found a path forward to successfully change the bitstream without having to rebuild the petalinux image.  I'm still hunting around for `petalinux/tools`, which is not installed by 2024.1 so probably a bitbake target, so it's possible to that `bootgen` BIF [method](https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/18841645/Solution+Zynq+PL+Programming+With+FPGA+Manager) might work also.

...  leaving notes for anyone in the future:

- Build the bitstream in Vivado
- run this [command](https://github.com/amaranth-lang/amaranth/issues/519) in Vivado's TCL cli: `set PROJ_PATH [get_property DIRECTORY [current_project]]; set PROJ [get_property NAME [current_project]]; write_cfgmem -force -format bin -interface smapx32 -disablebitswap -loadbit "up 0x0 $PROJ_PATH/$PROJ.runs/impl_1/ebaz4205_wrapper.bit" $PROJ_PATH/$PROJ.bin`
- transfer this bin file to the ebaz filesystem
- Follow the ["Using SysFs" instructions here](https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/18841645/Solution+Zynq+PL+Programming+With+FPGA+Manager), basically just run as root:
```
# echo 0 > /sys/class/fpga_manager/fpga0/flags
#  cp out.bin /lib/firmware/
#  echo out.bin > /sys/class/fpga_manager/fpga0/firmware 
```
dmesg shows the MII interface going down and back up (my ssh session didn't break):
```
[  384.310962] fpga_manager fpga0: writing out.bin to Xilinx Zynq FPGA Manager
[  384.500563] macb e000b000.ethernet eth0: Link is Down
[  387.620597] macb e000b000.ethernet eth0: unable to generate target frequency: 25000000 Hz
[  387.620828] macb e000b000.ethernet eth0: Link is Up - 100Mbps/Full - flow control off
```
No too bad...  though it does fail randomly...  I'm not sure if writing 1 to `flags`, then back to 0 makes it more reiliable...

**Comment by guido57** [comment]
Hi. 

Regarding the use of fpga manager:
1) the errror you had is evidently a permission error to write /lib/firmware/ebaz4205_wrapper.bin'
2) I know that fpga manager is not anymore supported in recent PetaLinux versions

To modify the programmable logic only, I use a JTAG programmer with Vivado.
